/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Appearance } from "./components/my-btn/appearance";
export namespace Components {
    interface MyBtn {
        "appearance": Appearance | undefined;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface MyTest {
    }
}
declare global {
    interface HTMLMyBtnElement extends Components.MyBtn, HTMLStencilElement {
    }
    var HTMLMyBtnElement: {
        prototype: HTMLMyBtnElement;
        new (): HTMLMyBtnElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLMyTestElement extends Components.MyTest, HTMLStencilElement {
    }
    var HTMLMyTestElement: {
        prototype: HTMLMyTestElement;
        new (): HTMLMyTestElement;
    };
    interface HTMLElementTagNameMap {
        "my-btn": HTMLMyBtnElement;
        "my-component": HTMLMyComponentElement;
        "my-test": HTMLMyTestElement;
    }
}
declare namespace LocalJSX {
    interface MyBtn {
        "appearance"?: Appearance | undefined;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface MyTest {
    }
    interface IntrinsicElements {
        "my-btn": MyBtn;
        "my-component": MyComponent;
        "my-test": MyTest;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-btn": LocalJSX.MyBtn & JSXBase.HTMLAttributes<HTMLMyBtnElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "my-test": LocalJSX.MyTest & JSXBase.HTMLAttributes<HTMLMyTestElement>;
        }
    }
}
